# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import scuc_pb2 as scuc__pb2


class SCUCStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSCUCResults = channel.unary_unary(
        '/SCUC/GetSCUCResults',
        request_serializer=scuc__pb2.SCUCinput.SerializeToString,
        response_deserializer=scuc__pb2.SCUCoutput.FromString,
        )


class SCUCServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSCUCResults(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SCUCServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSCUCResults': grpc.unary_unary_rpc_method_handler(
          servicer.GetSCUCResults,
          request_deserializer=scuc__pb2.SCUCinput.FromString,
          response_serializer=scuc__pb2.SCUCoutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SCUC', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
