# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scuc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scuc.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nscuc.proto\"N\n\tSCUCinput\x12\x17\n\x0fppc_method_name\x18\x01 \x01(\t\x12\x0f\n\x07ppcfile\x18\x02 \x01(\x0c\x12\x17\n\x08load_all\x18\x03 \x03(\x0b\x32\x05.LOAD\"*\n\x04LOAD\x12\x0b\n\x03\x62us\x18\x01 \x01(\x05\x12\x15\n\rload_of_a_day\x18\x02 \x03(\x01\"\x93\x01\n\nSCUCoutput\x12\x1d\n\x15termination_condition\x18\x01 \x01(\t\x12\x15\n\roptimal_value\x18\x02 \x01(\x01\x12\x17\n\x06status\x18\x03 \x03(\x0b\x32\x07.STATUS\x12\x15\n\x05power\x18\x04 \x03(\x0b\x32\x06.POWER\x12\x1f\n\npower_flow\x18\x05 \x03(\x0b\x32\x0b.POWER_FLOW\".\n\x06STATUS\x12\x0b\n\x03gen\x18\x01 \x01(\x05\x12\x17\n\x0fstatus_of_a_day\x18\x02 \x03(\x05\",\n\x05POWER\x12\x0b\n\x03gen\x18\x01 \x01(\x05\x12\x16\n\x0epower_of_a_day\x18\x02 \x03(\x01\"G\n\nPOWER_FLOW\x12\r\n\x05\x66_bus\x18\x01 \x01(\x05\x12\r\n\x05t_bus\x18\x02 \x01(\x05\x12\x1b\n\x13power_flow_of_a_day\x18\x03 \x03(\x01\x32\x33\n\x04SCUC\x12+\n\x0eGetSCUCResults\x12\n.SCUCinput\x1a\x0b.SCUCoutput\"\x00\x62\x06proto3')
)




_SCUCINPUT = _descriptor.Descriptor(
  name='SCUCinput',
  full_name='SCUCinput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ppc_method_name', full_name='SCUCinput.ppc_method_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ppcfile', full_name='SCUCinput.ppcfile', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='load_all', full_name='SCUCinput.load_all', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=92,
)


_LOAD = _descriptor.Descriptor(
  name='LOAD',
  full_name='LOAD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bus', full_name='LOAD.bus', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='load_of_a_day', full_name='LOAD.load_of_a_day', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=136,
)


_SCUCOUTPUT = _descriptor.Descriptor(
  name='SCUCoutput',
  full_name='SCUCoutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='termination_condition', full_name='SCUCoutput.termination_condition', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='optimal_value', full_name='SCUCoutput.optimal_value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='SCUCoutput.status', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power', full_name='SCUCoutput.power', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power_flow', full_name='SCUCoutput.power_flow', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=286,
)


_STATUS = _descriptor.Descriptor(
  name='STATUS',
  full_name='STATUS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gen', full_name='STATUS.gen', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_of_a_day', full_name='STATUS.status_of_a_day', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=334,
)


_POWER = _descriptor.Descriptor(
  name='POWER',
  full_name='POWER',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gen', full_name='POWER.gen', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power_of_a_day', full_name='POWER.power_of_a_day', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=380,
)


_POWER_FLOW = _descriptor.Descriptor(
  name='POWER_FLOW',
  full_name='POWER_FLOW',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f_bus', full_name='POWER_FLOW.f_bus', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='t_bus', full_name='POWER_FLOW.t_bus', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power_flow_of_a_day', full_name='POWER_FLOW.power_flow_of_a_day', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=453,
)

_SCUCINPUT.fields_by_name['load_all'].message_type = _LOAD
_SCUCOUTPUT.fields_by_name['status'].message_type = _STATUS
_SCUCOUTPUT.fields_by_name['power'].message_type = _POWER
_SCUCOUTPUT.fields_by_name['power_flow'].message_type = _POWER_FLOW
DESCRIPTOR.message_types_by_name['SCUCinput'] = _SCUCINPUT
DESCRIPTOR.message_types_by_name['LOAD'] = _LOAD
DESCRIPTOR.message_types_by_name['SCUCoutput'] = _SCUCOUTPUT
DESCRIPTOR.message_types_by_name['STATUS'] = _STATUS
DESCRIPTOR.message_types_by_name['POWER'] = _POWER
DESCRIPTOR.message_types_by_name['POWER_FLOW'] = _POWER_FLOW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SCUCinput = _reflection.GeneratedProtocolMessageType('SCUCinput', (_message.Message,), dict(
  DESCRIPTOR = _SCUCINPUT,
  __module__ = 'scuc_pb2'
  # @@protoc_insertion_point(class_scope:SCUCinput)
  ))
_sym_db.RegisterMessage(SCUCinput)

LOAD = _reflection.GeneratedProtocolMessageType('LOAD', (_message.Message,), dict(
  DESCRIPTOR = _LOAD,
  __module__ = 'scuc_pb2'
  # @@protoc_insertion_point(class_scope:LOAD)
  ))
_sym_db.RegisterMessage(LOAD)

SCUCoutput = _reflection.GeneratedProtocolMessageType('SCUCoutput', (_message.Message,), dict(
  DESCRIPTOR = _SCUCOUTPUT,
  __module__ = 'scuc_pb2'
  # @@protoc_insertion_point(class_scope:SCUCoutput)
  ))
_sym_db.RegisterMessage(SCUCoutput)

STATUS = _reflection.GeneratedProtocolMessageType('STATUS', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'scuc_pb2'
  # @@protoc_insertion_point(class_scope:STATUS)
  ))
_sym_db.RegisterMessage(STATUS)

POWER = _reflection.GeneratedProtocolMessageType('POWER', (_message.Message,), dict(
  DESCRIPTOR = _POWER,
  __module__ = 'scuc_pb2'
  # @@protoc_insertion_point(class_scope:POWER)
  ))
_sym_db.RegisterMessage(POWER)

POWER_FLOW = _reflection.GeneratedProtocolMessageType('POWER_FLOW', (_message.Message,), dict(
  DESCRIPTOR = _POWER_FLOW,
  __module__ = 'scuc_pb2'
  # @@protoc_insertion_point(class_scope:POWER_FLOW)
  ))
_sym_db.RegisterMessage(POWER_FLOW)



_SCUC = _descriptor.ServiceDescriptor(
  name='SCUC',
  full_name='SCUC',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=455,
  serialized_end=506,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSCUCResults',
    full_name='SCUC.GetSCUCResults',
    index=0,
    containing_service=None,
    input_type=_SCUCINPUT,
    output_type=_SCUCOUTPUT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCUC)

DESCRIPTOR.services_by_name['SCUC'] = _SCUC

# @@protoc_insertion_point(module_scope)
